name: Keploy API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  keploy-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        options: --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Install Keploy
        run: |
          curl -L -o keploy-linux https://github.com/keploy/keploy/releases/latest/download/keploy-linux
          chmod +x keploy-linux
          sudo mv keploy-linux /usr/local/bin/keploy

      - name: Run Keploy Tests
        run: |
          keploy test -c "node server.js" --delay 5
